# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S0a1ZTzBAbVixtVEzxfU981SSvGDczXj
"""

with open("hw2_data.txt", "r", encoding="utf-8") as file:
    lines = file.readlines()

# 初始化空的字典來存放詞彙計數
word_count = {}

# 逐行處理檔案內容
for line in lines:
    # 移除換行符號並分析每一個詞彙
    word = line.strip()
    # 如果詞彙已經在字典中，則增加計數；否則將詞彙加入字典並設置計數為1
    if word in word_count:
        word_count[word] += 1
    else:
        word_count[word] = 1

# 總共不重複的英文詞彙數
total_unique_words = len(word_count)

# 列印出每一個英文詞彙出現的次數
for word, count in word_count.items():
    print(f"英文詞彙 '{word}' 出現了 {count} 次")

print(f"總共有 {total_unique_words} 個不重複的英文詞彙")